# GitHub Pages Configuration for FastCV-LTS
title: "FastCV-LTS - Coming Soon"
description: "The Next Generation CV/Resume Builder - Fast, Modern, Professional"

# Simple configuration for GitHub Pages
# GitHub Pages will automatically serve index.html as the homepage